name: My Roomba 980
version: 0.1.1
slug: mmqttroomba
description: Roomba MQTT server based on Roomba980 python
url: https://github.com/Elwinmage/ha-mqtt-roomba-addon
arch:
- amd64
- aarch64
- armhf
- armv7
- i386
host_network: true
panel_title: My Roomba 980
panel_admin: false
uart: false
init: false
advanced: false
stage: stable
tmpfs: true
options:
  Roomba_IP: "192.168.0.99"
  Roomba_UID: ""
  Roomba_Password: ""
  MQTT_IP: "192.168.0.109"
  MQTT_PORT: 1883
  MQTT_USER: ""
  MQTT_PASSWORD: ""
  ACCOUNT_LOGIN: ""
  ACCOUNT_PASSWORD: ""
schema:
  Roomba_UID: str
  Roomba_Password: str
  Roomba_IP: str
  MQTT_IP: str
  MQTT_PORT: int
  MQTT_USER: str
  MQTT_PASSWORD: str
  ACCOUNT_LOGIN: str
  ACCOUNT_PASSWORD: password
debug: bool?
